apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-ingress-internal
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx-internal
  rules:
    - host: {{ .Values.domainPrefix }}.{{ .Values.global.domain.internal.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik
                port:
                  number: 80
