---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgDHWTb+f3bPDk0lv4M4wLvdFU1t0CGGbS7eAq94OngY0v55MbZhVPYjw9F7JvN7I5DLygsFe+G+zV/nu6gVetDfHrIRyX7xGQFvJmzcNJadbnN9/cyMj8oP9iKCVkEyE5t/PtX8SYxNZnOjOixEBsnQzfPQFu97C6T3qMCaBMouv/gvsAQ89MSwulP2yU3OyyjAoeoQl9fRyBp66dC3KjYvGjpJWOW1yM7Vb18IsxbsDMiLKETcDr3zN94hQVciql5CG4seYsKRVpntKw5BmiKeo8Kclfw6+YECnkVL0mYgD5fmRGnVDy8JqIrW5Sp7iJviMq2OGtzZ5JB9r6wjxdbd20rPYhT71W/5doC0IM6yoAyCNPUWU5dpd0ICFl2BAqyg065HjnviWvv5+5h0j7e6cmgza7TlA615ikPf9XMLsUnM05AuLt9Dbrqi+UinN2eteAgXYX9nYHtY9yTv6DW8ZIf1MQt5QJkliR2qDxKBrYkhZqaOx4Uu4Q2VHfErZz9HBaxUipFQBvjBt7UwvvL/4hWY8ePig+k5XP5I324vbLobsYzimoimEdDJUDtKlrfahnPYVqpJzP0gZkjaM1OBxlJa4daL7jtOmtV9JwhpPsgROKfSU3gNkNpqoYltO9g9upMBZ9gKUAmvrhFMLSoonr/bIsXVcM2KVVnlJGF69H2a+/BxrkPJCk3qpbcIqaYrAWv8cTU1qpo=
    AUTHENTIK_SECRET_KEY: AgBSFkTVxFaOjtKvLHKye3fyPnQKXXvFH3dk8RSfGs7AKCCYwR1MwaMyzH5tuqOOGq5n8GyYXnzDFW0ulsggxtcZPEAb6aJovqZ7ilI9a9yZadfORweyJwAqfJK7qPB7Tla7DzWAQ/YP6rXoYqUi5C49+TPz6k0yHl8+0EGPfWpv3jKPaYcpttb1DJixZLHAqKTilxyWxSPlkzZsOElES+YJGqzSj+qaYG+iYHxiawyLciEPj3P5L6oinYpSaGVg68ipSBKc0AltHfjkZZN53DlTEUkgA3K8QoQsGzPJiQs92fxEiRbZM4x3C4/1tlCUjCYsTAwjOrw0iq2JnkrtN3OK6gmZf57ykNw7X/Y9C4kI3gRBelXz83I+WjcqCYuqDr6L9fpNq8q2NqU5GqU5DVDs+9AA+IiVV6KwgeYcUH0luDw+I0EKWUsYjrHaEBBpnkgURZ8EUUEdyXrtH44nYd8X/yO58JdRxBFrQpYnQ7BMEW/8hFE7F/L+KZrWIdWEpsvfAJ6FfGym/2L88rBt9ky36/brIkB8svBe5gW/+TZ5hREnne/s8UxtpejHblGt1DVlq9/W7qESeQGutFGZIFTGlvB59Akn/dNUvjYpwBdilxAjTXN/YUbgERWIXJfFZ1/xNMqxPDK/P0q4ePpkx2chJQUYoXxj0q5mRaiRC+2/3xS+Z9PbIRqVdWW5UkL+GZ5M0AbLNstHFq6KdodctBPgMNxcaN6D/bJ6Hy+Nxeod5kdCfGVbGAuw9RRASg==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
