{{- if .Values.apps.readarr.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readarr-books-ingress-{{ .Values.instanceName }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.apps.readarr.domainPrefix }}.{{ .Values.global.domain.internal.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readarr-books-{{ .Values.instanceName }}
                port:
                  number: 8787
{{- end }}