apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudflare/helm-charts
    chart: charts/cloudflare-tunnel
    targetRevision: main
    helm:
      values: |
        cloudflare:
          secretName: cloudflared-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflared
    targetRevision: 0.4.7 # check for latest version
    helm:
      values: |
        tunnelName: <your-tunnel-name>
        cloudflared:
          image:
            tag: "2024.6.0" # check for latest
        config:
          ingress:
            - hostname: "app1.example.com"
              service: http://app1.namespace.svc.cluster.local:80
            - service: http_status:404
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated: {}