apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
spec:
  project: default
  source:
    repoURL: https://github.com/tomato4/homelab.git
    targetRevision: HEAD
    path: media-application-set
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
