apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
spec:
  project: default
  source:
    repoURL: https://github.com/tomato4/homelab.git
    targetRevision: HEAD
    path: plex
    helm:
      valueFiles:
        - values.yaml
        - ../global/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
