replicaCount: 1
namespace: plex

image:
  repository: plexinc/pms-docker
  tag: 1.41.6.9685-d301f511a
  pullPolicy: IfNotPresent

env:
  version: docker

domainPrefix: plex

volumes:
  config:
    size: 1Gi
    path: /mnt/storage/config/plex
  media:
    size: 100Gi
    path: /mnt/storage/media
