namespace: pihole
replicaCount: 1

image:
  repository: pihole/pihole
  tag: latest
  pullPolicy: IfNotPresent

volume:
  config:
    size: 1Gi
    path: /mnt/storage/config/pihole

domainPrefix: pihole
