apiVersion: v2
name: media
description:  Helm chart for media apps (Prowlarr, Radarr, Sonarr, Readarr)
version: 0.1.0
dependencies:
  - name: prowlarr
    version: 0.1.0
    repository: file://charts/prowlarr
    condition: apps.prowlarr.enabled
  - name: radarr
    version: 0.1.0
    repository: file://charts/radarr
    condition: apps.radarr.enabled
  - name: sonarr
    version: 0.1.0
    repository: file://charts/sonarr
    condition: apps.sonarr.enabled
  - name: readarr
    version: 0.1.0
    repository: file://charts/readarr
    condition: apps.readarr.enabled
