apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-plex-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/storage/config/plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-plex-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: config-plex-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: plex
  template:
    metadata:
      labels:
        name: plex
    spec:
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: config-plex-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
      containers:
        - name: plex
          image: plexinc/pms-docker
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 60
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /media
              name: media
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1002"
            - name: VERSION
              value: "docker"
            - name: TZ
              value: "Europe/Prague"
#            - name: PLEX_CLAIM
#              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  selector:
    name: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: media
spec:
  rules:
    - host: plex.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
---
#apiVersion: tailscale.com/v1alpha1
#kind: IngressRoute
#metadata:
#  name: plex-ingress-tailscale
#  namespace: media
#spec:
#  entryPoints:
#    - web
#  routes:
#    - match: Host(`plex.tailbe373.ts.net`)  # This will be the Tailscale domain
#      kind: Rule
#      services:
#        - name: plex
#          port: 32400
