apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-prowlarr-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/config/prowlarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-prowlarr-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: config-prowlarr-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
        - name: route-via-vpn
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              set -e
              echo "🔍 Discovering VPN pod IP via DNS..."
              VPN_IP=$(getent hosts vpn-gateway.media.svc.cluster.local | awk '{ print $1 }')
      
              if [ -z "$VPN_IP" ]; then
                echo "❌ ERROR: Could not resolve VPN pod IP"
                exit 1
              fi
      
              echo "✅ VPN IP resolved: $VPN_IP"
      
              echo "🔍 Discovering current default gateway (K8s node gateway)..."
              K8S_GATEWAY=$(ip route | awk '/default/ {print $3}')
      
              if [ -z "$K8S_GATEWAY" ]; then
                echo "❌ ERROR: Could not find K8s gateway IP"
                exit 1
              fi
      
              echo "✅ K8s gateway is: $K8S_GATEWAY"
      
              echo "🛠️  Rewriting routes..."
              ip route del default
              ip route add default via $VPN_IP
              ip route replace 10.42.0.0/16 via $K8S_GATEWAY
              ip route replace 10.43.0.0/16 via $K8S_GATEWAY
              echo "✅ Routing updated."
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1002"
            - name: TZ
              value: "Europe/Prague"
          volumeMounts:
            - name: config
              mountPath: /config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-prowlarr-pvc
        - name: vpn-config
          projected:
            sources:
              - secret:
                  name: windscribe-auth
                  items:
                    - key: ovpn
                      path: client.ovpn
                    - key: auth.txt
                      path: auth.txt
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  selector:
    app: prowlarr
  ports:
    - port: 9696
      targetPort: 9696
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-ingress
  namespace: media
spec:
  rules:
    - host: prowlarr.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696
