#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: media-movies-pv
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/storage/media/movies"
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: media-movies-pvc
#  namespace: media
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Gi
#  volumeName: media-movies-pv
#  storageClassName: ""
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: media-series-pv
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/storage/media/series"
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: media-series-pvc
#  namespace: media
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Gi
#  volumeName: media-series-pv
#  storageClassName: ""
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: media-books-pv
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/storage/media/books"
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: media-books-pvc
#  namespace: media
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Gi
#  volumeName: media-books-pv
#  storageClassName: ""
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-legacy
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc-legacy
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: media-pv-legacy
  storageClassName: ""
