apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/storage/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: media-movies-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-series-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/media/series"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-series-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: media-series-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: media-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/media/downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: media-downloads-pv
  storageClassName: ""
