apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-readarr-books-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/config/readarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-readarr-books-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: config-readarr-books-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr-books
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: readarr-books
  template:
    metadata:
      labels:
        app: readarr-books
    spec:
      containers:
        - name: readarr
          image: lscr.io/linuxserver/readarr:develop
          ports:
            - containerPort: 8787
          volumeMounts:
            - name: config
              mountPath: /config
#            - name: books
#              mountPath: /books
#            - name: downloads
#              mountPath: /downloads
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1002"
            - name: TZ
              value: "Europe/Prague"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-readarr-books-pvc
