{{- if .Values.defineGlobalPvc.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-media-pv
spec:
  capacity:
    storage: {{ .Values.volume.media.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.media.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.media.size }}
  volumeName: media-media-pv
  storageClassName: ""
{{- end }}