{{- if .Values.defineGlobalPvc.enabled | default false }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-prowlarr-pv
spec:
  capacity:
    storage: {{ .Values.prowlarr.volume.config.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.prowlarr.volume.config.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-prowlarr-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prowlarr.volume.config.size }}
  volumeName: config-prowlarr-pv
  storageClassName: ""
{{- end }}