namespace: authentik
domainPrefix: authentik

authentik:
  global:
    envFrom:
      - secretRef:
          name: authentik-secrets

  redis:
    enabled: true

  postgresql:
    enabled: true
    primary:
      extraEnvVars:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: AUTHENTIK_POSTGRESQL__PASSWORD
