apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      name: plex
  template:
    metadata:
      labels:
        name: plex
    spec:
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: config-plex-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
      containers:
        - name: plex
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 60
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /media
              name: media
          env:
            - name: PLEX_UID
              value: "{{ .Values.global.user.uid }}"
            - name: PLEX_GID
              value: "{{ .Values.global.user.gid }}"
            - name: VERSION
              value: "{{ .Values.env.version }}"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
