apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress-external
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx-external
  rules:
    - host: {{ .Values.domainPrefix }}.{{ .Values.global.domain.public.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
