apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress-external
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Host 192.168.0.1;
spec:
  ingressClassName: nginx-internal
  rules:
    - host: {{ .Values.domainPrefix }}.{{ .Values.global.domain.public.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
