apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - --metrics=0.0.0.0:3333
            - run
            - --token
            - /etc/cloudflared/token
          livenessProbe:
            httpGet:
              path: /ready
              port: 3333
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /ready
              port: 3333
              scheme: HTTP
            failureThreshold: 6
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config/config.yaml
              subPath: config.yaml
            - name: token
              mountPath: /etc/cloudflared/token
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
        - name: token
          secret:
            secretName: cloudflared-token
