apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-{{ .Values.global.instanceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: radarr-{{ .Values.global.instanceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: radarr-{{ .Values.global.instanceName }}
  template:
    metadata:
      labels:
        app: radarr-{{ .Values.global.instanceName }}
    spec:
      containers:
        - name: radarr
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
{{/*          ports:*/}}
{{/*            - containerPort: 7878*/}}
          env:
            - name: PUID
              value: "{{ .Values.global.user.uid }}"
            - name: PGID
              value: "{{ .Values.global.user.gid }}"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: {{ .Values.global.instanceName }}
            - name: media
              mountPath: /movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-radarr-pvc
        - name: media
          persistentVolumeClaim:
              claimName: media-pvc
