apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress-{{ .Values.global.instanceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  ingressClassName: nginx-internal
  rules:
    - host: {{ .Values.domainPrefix }}.{{ .Values.global.domain.internal.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr-{{ .Values.global.instanceName }}
                port:
                  number: 7878
