apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      volumes:
        - name: pihole-config
          persistentVolumeClaim:
            claimName: pihole-config-pvc
      containers:
        - name: pihole
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 53
              hostPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              hostPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: pihole-config
              mountPath: /etc/pihole
          env:
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: PIHOLE_UID
              value: "{{ .Values.global.user.uid }}"
            - name: PIHOLE_GID
              value: "{{ .Values.global.user.gid }}"
