apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config-pv
spec:
  capacity:
    storage: {{ .Values.volume.config.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.config.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.config.size }}
  volumeName: pihole-config-pv
  storageClassName: ""
