apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre-web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /books
              name: books
          env:
            - name: PUID
              value: "{{ .Values.global.user.uid }}"
            - name: PGID
              value: "{{ .Values.global.user.gid }}"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-calibre-pvc
        - name: books
          persistentVolumeClaim:
            claimName: calibre-pvc
