apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.volumes.books.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.volumes.books.path }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.books.size }}
  volumeName: calibre-pv
  storageClassName: ""
