apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress-external
  namespace: argocd
spec:
  ingressClassName: nginx-external
  rules:
#   TODO: Change host to values
    - host: argo.glazrtom.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80