apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: calibre
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre-web
          image: linuxserver/calibre-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /books
              name: books
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1002"
            - name: TZ
              value: "Europe/Prague"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-calibre-pvc
        - name: books
          persistentVolumeClaim:
            claimName: calibre-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: calibre
  namespace: calibre
spec:
  selector:
    app: calibre
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-ingress
spec:
  rules:
    - host: calibre.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre
                port:
                  number: 80
