apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-pv
  namespace: calibre
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/media/calibre"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-pvc
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: calibre-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-calibre-pv
  namespace: calibre
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/config/calibre"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-calibre-pvc
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: config-calibre-pv
  storageClassName: ""
