apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  labels:
    app: authentik-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-server
  template:
    metadata:
      labels:
        app: authentik-server
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["server"]
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: SECRET_KEY
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: {{ .Release.Name }}-postgresql
            - name: AUTHENTIK_POSTGRESQL__USER
              value: {{ .Values.postgresql.auth.username }}
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: POSTGRESQL_PASSWORD
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: AUTHENTIK_REDIS__HOST
              value: {{ .Release.Name }}-redis-master
          ports:
            - containerPort: 9000
