---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgB1VCUSO4jkC/FakCqdSc0IfM3DKkfNZVqm2D9Ra8vZRqS2SJH8cZ9zS42cGVU9y9aytP1tV8wSQ8dXU43JB+EN6d+c1PcPt2jZZnXyfWNFbD5pF4D28h27TjhQHyC3HJyvpAJkEueT19RTGADWHQPvWnVOybWa4BOCAOYsf/RVgy7ygh0FeVKOqzYNcDcbsfQXJ/yDob/mQ/N+C8iMH3pzvVPLQ9FRe8rBVXn42neUVbCtnsqYHbN8zPKwnPaKjJk3Nt9vqkVhoK0VqteBs3OB6rQNqdRU42o5GcAz8B+U9BIjKZ89HE1K+z/v4bH68gYSpS+wSlW+b8JYT6K5n1j7rbOetvwvQ3xFmiYtG8LZ+xv6a18oBe+PCfHIhfKPv/ZejmOFjdujNthJu+9SvaZsupu/J92maGEC1nOeiwhs2DT24T+sClvx3dB5W9TiLfTvnq1/a5k4cBLFfzaJOsDGRzl/i79yvvh4O0bhvA5VFfoKCZqphbMpeLPhGb76JaCZ/O70bL2RIcuKxs2OwweXwuNEF6Iqw//TAK7lATRGiSqkA2Nauv1kWDB6lV1wrMYvS0oiNJ5ByiHyy1l9kfu2LgOcOMjxkv895sDPm5Q4mOh7qGsYJPhYUCM5C/HYbOYVb0pG3wJNBSBVeyktQRG7kbiuCBLAlieTcdvTVczSwACEKIEmmaQPixLFOVb7g1Lb3A+E7qVYVLojBDHfW1HQNCnhUmp0Grq1xrDBbQHaPj4rI5Tj/OX9lcD09Q==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
