apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-external
  namespace: ingress
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: ingress
  version: 36.1.0
  valuesContent: |-
    service:
      type: ClusterIP
    ingressClass:
      isDefaultClass: false
      name: traefik-external
    additionalArguments:
      - --providers.kubernetesingress.ingressclass=traefik-external
