apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: PUID
              value: "{{ .Values.global.user.uid }}"
            - name: PGID
              value: "{{ .Values.global.user.gid }}"
            - name: OPENVPN_PROVIDER
              value: "{{ .Values.env.openvpnProvider }}"
            - name: OPENVPN_CONFIG
              value: "{{ .Values.env.openvpnConfig }}"
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.usernameKey }}
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.passwordKey }}
            - name: TRANSMISSION_WEB_UI
              value: "{{ .Values.env.webUI }}"
            - name: LOCAL_NETWORK
              value: "{{ .Values.env.localNetwork }}"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: transmission-media-pvc
