---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    authentik-postgresql: AgBfG69UB/SPHudnR1axHHfOo8mQ1V0DtHCRxtnspr8dax9Flj4W5VumLyWPlwKXjDk1kGySJ3D/Qd1GbB+rbf/64s8bc6DoafrZPzttiGuY5J3yb/8OjvPMVmsToZaoUYqzB17f1FcR7vJ7fQub1OZfyDGOc6A/9r0o6OSnzycbPsbcA+79T53Pw/TXjua9h756J0t77qoSvlseWVOLx1QOkp/OSgguE612YiJWn9YPRa6T0KuFqoJI9wuO+UZ/TzRGXcxm3aQllMoAnIG8FE3Qdag6uhacThmS5Rp49sIanD0HF0uqVtk0MMRIjRWxPwZbI9x3YvTU0qf4pM7UunzQyPMDfIQFpnuoirRWuQZJDGVmUAaRD2hycpxCk7FG2cT+FKAf/oVzyhgrQMVTLvKseARSPRKkrGpdIbI7jzzfnjQIWd+6ZKrm7gCvjxr9CxgoaSxH13STlfzNaF1okMxMoTe/mGYXoU16DEVfs9ykRUlndcto7IzSf6ZqyYwp0EmRvt7u18cw9W1cs1GqbY6STaP6QWwY1RRd/AZNAM4zJ/twOhiib69Y0pJLoWUKpy7qMKh/YeDZmMg57wVGl3Hc/ukOjH5Od+eSt+SzHtkDtZSGwFIm3uObaK6ZTP31lhy4teQGCnL/XfBS/MJnSyeuEYy0hn7jwVPI/jMjXCcDXiC+xjlMyCH4KarF0EACBnWts2sGk7RPRsMayikKdVBkz0z2GtRQd9VP0DC/Af748qkT3rt/kMf+zpUn6g==
    authentik-secret: AgAOVc4RQiM97M6m5CPfAuxaewguOGoX6kl2PriuAv47qT5sxQ6Sm3jEqF7mVqMLUK8J4F7l8XyYlSG1SxONM7MTMhZG+HbmkDRNbl20UjDLPK0z/0IDtQ02nbeNGBZ7mXIYMwc2FXNjg4yixTVDyFl79gect6JQt0qb8tKN49sgUvZnaGktxSPpPhGrto4bC2yzCOGaySFB54oX4R5c90l1ezsMAlBV0fltxkt7y1vqI9p/qBHe/uwiGRdFfVlQfi62xxsxQTS/5qJUmMIeDqWimjAT57Rsj50bLZTm89eDD40g/1GFVBpahEghc2+do2sTQv5X9QnmDVOQan0A3zIojAuhMbjfempXKcwkaxw8iVsU0HjjzP8k5wi4nxVHfXh73mfVh21XseQiVmOmVvtURC7IeYHxETR+lAdb8aFOj+zjRiLy8DbqkSgdYI8TLvJCQXLzK4+gR7I8SkrfdP3ELN08tlSbl7yu0N1+0twu0COz/JU+LWmbw2K1/ddQIPgT+9uOjMgrY+oaUFiQ+kgeFc3Vm3cOgb3hmuTlJ2fvHUuPzti/DmuExLgSSpBN4U9IDJ/1gqEfOLpMi1LNK80hPxDCBygNH6UYBWoxeNR1S0J0odrvMtmA5+FF8ehxtZ+YtFBRMXQqs0Jl0bRZDmFMZHuU4IIdkOLHWOdfWVGdVbJzjKWHkCIUoH43jG3Mlbz6TA5PdELD2S1hWxGX+kH44RipO8giYOhg28QcfAcjscwWs7WWvgD+dCxuDA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
