apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-nginx-config
  namespace: plex
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      location / {
        proxy_pass http://plex:32400;
        proxy_set_header Host $host;
        proxy_set_header Referer 192.168.0.100;
        proxy_set_header X-Real-IP 192.168.0.100;
        proxy_set_header X-Forwarded-For 192.168.0.100;
      }
    }
