apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-nginx
  namespace: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-nginx
  template:
    metadata:
      labels:
        app: plex-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: plex-nginx-config
