apiVersion: v1
kind: Service
metadata:
  name: plex-nginx
  namespace: plex
spec:
  selector:
    app: plex-nginx
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 8080
  type: ClusterIP
