apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-{{ .Values.global.instanceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: sonarr-{{ .Values.global.instanceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: sonarr-{{ .Values.global.instanceName }}
  template:
    metadata:
      labels:
        app: sonarr-{{ .Values.global.instanceName }}
    spec:
      containers:
        - name: sonarr
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
{{/*          ports:*/}}
{{/*            - containerPort: 8989*/}}
          env:
            - name: PUID
              value: "{{ .Values.global.user.uid }}"
            - name: PGID
              value: "{{ .Values.global.user.gid }}"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: {{ .Values.global.instanceName }}
            - name: media
              mountPath: /movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-sonarr-pvc
        - name: media
          persistentVolumeClaim:
              claimName: media-pvc
