{{- if .Values.apps.sonarr.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress-{{ .Values.instanceName }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.apps.sonarr.domainPrefix }}.{{ .Values.global.domain.internal.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr-{{ .Values.instanceName }}
                port:
                  number: 8989
{{- end }}