{{- if .Values.apps.sonarr.enabled | default false }}
apiVersion: v1
kind: Service
metadata:
  name: sonarr-{{ .Values.instanceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sonarr-{{ .Values.instanceName }}
  ports:
    - port: 8989
      targetPort: 8989
{{- end }}
