apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
spec:
  project: default
  source:
    repoURL: https://github.com/tomato4/homelab.git
    targetRevision: HEAD
    path: transmission
    helm:
      valueFiles:
        - values.yml
        - ../global/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: transmission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
