apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: haugene/transmission-openvpn
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENVPN_PROVIDER
              value: "WINDSCRIBE"
            - name: OPENVPN_CONFIG
              value: "Prague-Vltava-udp"
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: windscribe-auth
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: windscribe-auth
                  key: password
            - name: TRANSMISSION_WEB_UI
              value: "combustion"
            - name: LOCAL_NETWORK
              value: "10.42.0.0/16"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data/media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: transmission-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: transmission
spec:
  selector:
    app: transmission
  ports:
    - port: 80
      targetPort: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-ingress
  namespace: transmission
spec:
  rules:
    - host: transmission.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: 9091
