replicaCount: 1
namespace: transmission

image:
  repository: haugene/transmission-openvpn
  pullPolicy: IfNotPresent
  tag: latest

env:
  openvpnProvider: "WINDSCRIBE"
  openvpnConfig: "Prague-Vltava-udp"
  webUI: "flood-for-transmission"
  localNetwork: "10.42.0.0/16"

domainPrefix: transmission

volumes:
  config:
    size: 1Gi
    path: /mnt/storage/config/transmission
  media:
    size: 100Gi
    path: /mnt/storage/media

secrets:
  name: windscribe-auth
  usernameKey: username
  passwordKey: password
